# Generated by Django 4.2 on 2023-07-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wageregister',
            name='sunday_and_holidays',
        ),
    ]
